// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-elders.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_elders_default = defineTool({
  name: "list_elders",
  title: "List elders",
  description: "List all elders (elderly patients) the signed-in Sentio user has access to, with age, phone, language, and medical conditions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("elders").select("id, name, age, phone, preferred_language, medical_conditions, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { elders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-elder-details.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_elder_details_default = defineTool2({
  name: "get_elder_details",
  title: "Get elder details",
  description: "Get a full profile for one elder: demographics, medical conditions, current medicines, and the most recent check-in summary.",
  inputSchema: {
    elder_id: z.string().uuid().describe("Elder UUID from list_elders.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ elder_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const [elderRes, medsRes, lastCheckInRes] = await Promise.all([
      supabase.from("elders").select("*").eq("id", elder_id).maybeSingle(),
      supabase.from("medicines").select("name, dosage, timing, purpose").eq("elder_id", elder_id),
      supabase.from("check_ins").select("created_at, sentiment, well_being_score, medicines_taken, symptoms_reported, conversation_summary").eq("elder_id", elder_id).order("created_at", { ascending: false }).limit(1).maybeSingle()
    ]);
    if (elderRes.error || !elderRes.data) {
      return {
        content: [{ type: "text", text: elderRes.error?.message ?? "Elder not found" }],
        isError: true
      };
    }
    const payload = {
      elder: elderRes.data,
      medicines: medsRes.data ?? [],
      last_check_in: lastCheckInRes.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-recent-checkins.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_recent_checkins_default = defineTool3({
  name: "list_recent_checkins",
  title: "List recent check-ins",
  description: "List recent AI voice/WhatsApp check-ins for one elder, most recent first. Returns sentiment, well-being score, medicines taken, symptoms and summary.",
  inputSchema: {
    elder_id: z2.string().uuid().describe("Elder UUID from list_elders."),
    limit: z2.number().int().min(1).max(30).default(10).describe("How many check-ins to return (1-30).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ elder_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.from("check_ins").select(
      "id, created_at, check_in_type, sentiment, well_being_score, medicines_taken, symptoms_reported, conversation_summary"
    ).eq("elder_id", elder_id).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { check_ins: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-alerts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_alerts_default = defineTool4({
  name: "list_alerts",
  title: "List alerts",
  description: "List health/emergency alerts for elders the signed-in user has access to. Filter by elder or by unresolved status.",
  inputSchema: {
    elder_id: z3.string().uuid().optional().describe("Optional elder UUID to filter by."),
    only_unresolved: z3.boolean().default(true).describe("If true, only return alerts that have not been resolved."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ elder_id, only_unresolved, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    let query = supabase.from("alerts").select("id, elder_id, alert_type, severity, message, resolved, created_at").order("created_at", { ascending: false }).limit(limit);
    if (elder_id) query = query.eq("elder_id", elder_id);
    if (only_unresolved) query = query.eq("resolved", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { alerts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hcdwbpbvuvbrozttahfz";
var mcp_default = defineMcp({
  name: "sentio-mcp",
  title: "Sentio AI",
  version: "0.1.0",
  instructions: "Sentio AI monitors elderly patients through voice and WhatsApp check-ins. Use list_elders to find elders the signed-in user cares for, then get_elder_details for a profile, list_recent_checkins for recent AI conversations, and list_alerts for outstanding health/emergency alerts.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_elders_default, get_elder_details_default, list_recent_checkins_default, list_alerts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
